"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = config(
    "SECRET_KEY", default="chave-temporaria-apenas-para-desenvolvimento"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="", cast=Csv())


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "django_filters",
    "produtos",
    "pedidos",
    "usuarios",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# Upload real de imagem de Produto pelo Django Admin (Produto.imagem,
# produtos/models.py) — armazenamento local em disco, servido via
# core/urls.py's static() apenas quando DEBUG=True. Solução intermediária,
# não produção-ready: mesma pendência já documentada para imagem_url (ver
# docs/produtos.md) sobre migrar para um serviço de hospedagem real.
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"


CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS", default="http://localhost:5173", cast=Csv()
)

CORS_ALLOW_CREDENTIALS = True


CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS", default="http://localhost:5173", cast=Csv()
)

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "core.authentication.CookieJWTAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "login": "5/min",
        "registro": "5/min",
        # Public (AllowAny — see pedidos/views.py::FreteCalcularView) and
        # each call is a real request against SuperFrete's API using our
        # token, so it needs the same public+throttled treatment as
        # login/registro above. 20/min is generous for legitimate use
        # (re-quoting after a CEP/cart change during one checkout session)
        # while still bounding how much of our SuperFrete quota an
        # unauthenticated client can burn through.
        "frete": "20/min",
        # Público (AllowAny — ver pedidos/views.py::InfinitePayWebhookView) e
        # cada chamada legítima já dispara uma requisição de volta pra API da
        # InfinitePay (payment_check, ver pedidos/services/infinitepay.py)
        # pra confirmar o pagamento antes de confiar no corpo do webhook —
        # mesma lógica de "endpoint público custa uma chamada externa" do
        # `frete` acima, só que o volume esperado aqui é por pedido pago (não
        # por visitante navegando o carrinho), então o limite é bem mais
        # folgado.
        "infinitepay_webhook": "100/min",
    },
}

# SuperFrete (cálculo de frete) — see pedidos/services/superfrete.py
SUPERFRETE_TOKEN = config("SUPERFRETE_TOKEN", default="")
# Sem hífen (8 dígitos) — formato exigido pela API da SuperFrete
# (confirmado via requisição real contra o sandbox), não o formato com
# hífen usado nas telas do checkout (ex: "72017-212").
SUPERFRETE_CEP_ORIGEM = config("SUPERFRETE_CEP_ORIGEM", default="")
# Sandbox/produção usam hosts diferentes (não apenas paths) — mesmo padrão
# já usado em CORS_ALLOW_ALL_ORIGINS acima: o ambiente (DEBUG) decide, sem
# precisar de mais uma variável de ambiente separada. O token do sandbox
# (hoje em .env) não funciona contra a URL de produção nem vice-versa, então
# os dois já precisam estar sincronizados manualmente ao trocar de ambiente.
SUPERFRETE_BASE_URL = (
    "https://sandbox.superfrete.com" if DEBUG else "https://api.superfrete.com"
)

# InfinitePay (link de pagamento) — ver pedidos/services/infinitepay.py.
# Handle da conta InfinitePay que recebe o pagamento (ex: "renato-ramos-0g5",
# a tag pública "$handle" da conta, sem o "$") — hoje aponta pra conta
# pessoal de dev/teste do desenvolvedor, precisa ser trocado pelo handle da
# conta do cliente antes de ir pra produção. Diferente da SuperFrete, a API
# da InfinitePay não distingue sandbox/produção por host nem exige um token
# de autenticação por requisição — qualquer chamada a POST .../links que
# souber um handle válido gera um link de cobrança pra aquela conta (o
# handle em si já funciona como identificador público, tipo um
# "usuário.pagar.me/handle"); por isso não existe INFINITEPAY_BASE_URL
# alternável por DEBUG aqui, só essa credencial.
INFINITEPAY_HANDLE = config("INFINITEPAY_HANDLE", default="")

# URLs públicas do próprio site — usadas para montar `redirect_url` (pra onde
# a InfinitePay manda o cliente de volta após o pagamento) e `webhook_url`
# (pra onde a InfinitePay notifica o pagamento confirmado) na criação do link
# de pagamento. Não existiam variáveis assim no projeto até agora porque
# nenhuma outra integração precisava que o backend soubesse sua própria URL
# pública nem a do frontend — SuperFrete e o próprio frontend sempre foram
# quem chama o backend, nunca o contrário. Defaults cobrem o ambiente de dev
# local (frontend Vite em 5173, backend em 8000); em produção ambas precisam
# apontar pros domínios reais.
FRONTEND_URL = config("FRONTEND_URL", default="http://localhost:5173")
BACKEND_URL = config("BACKEND_URL", default="http://localhost:8000")
