# Generated by Django 6.0.1 on 2026-07-16 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_itempedido_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='user',
            new_name='usuario',
        ),
    ]
