# Generated by Django 6.0.1 on 2026-07-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_pedido_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='produto_nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='produto_tamanho',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
