# Generated by Django 6.0.1 on 2026-07-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_itempedido_produto_nome_itempedido_produto_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='frete_nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='frete_prazo_dias',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='frete_transportadora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='frete_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
