# Generated by Django 6.0.1 on 2026-08-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_pedido_frete_nome_pedido_frete_prazo_dias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='link_pagamento_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
