# Generated by Django 6.0.1 on 2026-08-11 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_pedido_link_pagamento_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoTrocaDevolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('troca', 'Troca'), ('devolucao', 'Devolução')], max_length=20)),
                ('motivo', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em análise'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('concluida', 'Concluída')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_troca_devolucao', to='pedidos.itempedido')),
            ],
            options={
                'verbose_name': 'Solicitação de Troca/Devolução',
                'verbose_name_plural': 'Solicitações de Troca/Devolução',
            },
        ),
    ]
