# Generated by Django 6.0.1 on 2026-02-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.CharField(default='Sem Marca', max_length=50),
            preserve_default=False,
        ),
    ]
