# Generated by Django 6.0.1 on 2026-04-12 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produtos", "0003_marca_alter_variacao_options_alter_produto_marca"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variacao",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variacoes",
                to="produtos.produto",
            ),
        ),
    ]
