# Generated by Django 6.0.1 on 2026-04-17 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("produtos", "0004_alter_variacao_produto"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="variacao",
            unique_together={("produto", "tamanho")},
        )
    ]
