# Generated by Django 6.0.1 on 2026-07-16 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_alter_categoria_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome']},
        ),
    ]
