# Generated by Django 6.0.1 on 2026-07-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_alter_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacao',
            name='altura',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='variacao',
            name='comprimento',
            field=models.IntegerField(default=35),
        ),
        migrations.AddField(
            model_name='variacao',
            name='largura',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='variacao',
            name='peso',
            field=models.DecimalField(decimal_places=3, default=0.3, max_digits=5),
        ),
    ]
