# Generated by Django 6.0.1 on 2026-08-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_variacao_altura_variacao_comprimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
