# Generated by Django 6.0.1 on 2026-08-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_produto_criado_em_produto_em_outlet_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='detalhes',
            field=models.TextField(blank=True),
        ),
    ]
