# Generated by Django 6.0.1 on 2026-08-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0013_favorito'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variacao',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='variacao',
            name='cor',
            field=models.CharField(default='Único', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='variacao',
            unique_together={('produto', 'tamanho', 'cor')},
        ),
    ]
